import Head from 'next/head'
import {
  Container,
  Main,
  Title,
} from '../components/sharedstyles'
import {MarkdownPreview} from '../components/MarkdownPreview'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>

        <MarkdownPreview />
      </Main>
    </Container>
  )
}
