import Head from "next/head";
import { Main, Title } from "../components/sharedstyles";
import { MarkdownPreview } from "../components/MarkdownPreview";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main>
                <Title>
                    <a href="#">Read about Markdown remark & rehype Converter</a> 
                </Title>

                <MarkdownPreview />
            </Main>
        </>
    );
}
